# Generated by Django 4.2.23 on 2025-08-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='tech_stack',
            field=models.CharField(max_length=250),
        ),
    ]
