# Generated by Django 4.2.23 on 2025-08-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_projectmodel_tech_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='priject_image',
            new_name='project_image',
        ),
    ]
